




/*
 * This is a generated file. Do not edit this file.
 */
package examples.security.providers.identityassertion.simple;

import java.util.*;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.zip.CRC32;
import weblogic.descriptor.*;
import weblogic.descriptor.BeanUpdateEvent.PropertyUpdate;
import weblogic.descriptor.internal.*;
import weblogic.descriptor.internal.ReferenceManager.Resolver;
import weblogic.descriptor.beangen.LegalChecks;
import weblogic.descriptor.beangen.StringHelper;
import weblogic.utils.ArrayUtils;
import weblogic.utils.StringUtils;
import weblogic.utils.Debug;
import weblogic.utils.collections.ArrayIterator;
import weblogic.utils.collections.CombinedIterator;
import weblogic.descriptor.internal.Munger.ReaderEventInfo;

import weblogic.management.commo.RequiredModelMBeanWrapper;


/**
 * Corresponds to SimpleSampleIdentityAsserterMBean
 * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean)
 * @author Copyright (c) 2003,2014, Oracle and/or its affiliates. All rights reserved.
 * @version 0.1
 *
 * No description provided.
 *
 * @xsdgen:complexType.typeName simple-sample-identity-asserterType
 * @xsdgen:complexType.targetNamespace http://xmlns.oracle.com/weblogic/security/extension
 * @xsdgen:complexType.rootElement simple-sample-identity-asserter
 */
public class SimpleSampleIdentityAsserterMBeanImpl
  extends weblogic.management.security.authentication.IdentityAsserterMBeanImpl
  implements SimpleSampleIdentityAsserterMBean, java.io.Serializable
{
  private String[] _ActiveTypes;
  private boolean _Base64DecodingRequired;
  private String _CompatibilityObjectName;
  private String _Description;
  private String _Name;
  private String _ProviderClassName;
  private weblogic.management.security.RealmMBean _Realm;
  private String[] _SupportedTypes;
  private String _Version;
  private transient SimpleSampleIdentityAsserterImpl _customizer;


  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=SimpleSampleIdentityAsserterMBeanImpl)
   *
   */
  public SimpleSampleIdentityAsserterMBeanImpl() {
    super();
    _initializeRootBean(getDescriptor());
    try {
      _customizer = new examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterImpl(new RequiredModelMBeanWrapper(this));
    } catch (Exception e) {
      if (e instanceof RuntimeException)
        throw (RuntimeException)e;
      throw new java.lang.reflect.UndeclaredThrowableException(e);
    }
    _initializeProperty(-1);
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=SimpleSampleIdentityAsserterMBeanImpl)
   *
   */
  public SimpleSampleIdentityAsserterMBeanImpl(weblogic.descriptor.DescriptorBean param0, int param1) {
    super(param0, param1);
    _initializeRootBean(getDescriptor());
    try {
      _customizer = new examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterImpl(new RequiredModelMBeanWrapper(this));
    } catch (Exception e) {
      if (e instanceof RuntimeException)
        throw (RuntimeException)e;
      throw new java.lang.reflect.UndeclaredThrowableException(e);
    }
    _initializeProperty(-1);
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=SimpleSampleIdentityAsserterMBeanImpl)
   *
   */
  public SimpleSampleIdentityAsserterMBeanImpl(weblogic.descriptor.DescriptorBean param0, int param1, boolean param2) {
    super(param0, param1);
    _setTransient(param2);
    _initializeRootBean(getDescriptor());
    try {
      _customizer = new examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterImpl(new RequiredModelMBeanWrapper(this));
    } catch (Exception e) {
      if (e instanceof RuntimeException)
        throw (RuntimeException)e;
      throw new java.lang.reflect.UndeclaredThrowableException(e);
    }
    _initializeProperty(-1);
  }

  /**
   * No description provided.
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=getProviderClassName)
   *
   * @xsdgen:element.exclude
   * @transient
   */
  public String getProviderClassName() {
    return _ProviderClassName;
  }

  /**
   * No description provided.
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=getSupportedTypes)
   *
   * @xsdgen:element.exclude
   * @transient
   */
  public String[] getSupportedTypes() {
    return _SupportedTypes;
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=isProviderClassNameInherited)
   *
   * return true if the value of property ProviderClassName is inherited from template
   */
  public boolean isProviderClassNameInherited() {
    return false;
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=isProviderClassNameSet)
   *
   * @xsdgen:isSetMethodFor provider-class-name
   */
  public boolean isProviderClassNameSet() {
    return _isSet(2);
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=isSupportedTypesInherited)
   *
   * return true if the value of property SupportedTypes is inherited from template
   */
  public boolean isSupportedTypesInherited() {
    return false;
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=isSupportedTypesSet)
   *
   * @xsdgen:isSetMethodFor supported-type
   */
  public boolean isSupportedTypesSet() {
    return _isSet(8);
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=setProviderClassName)
   *
   */
  public void setProviderClassName(String param0)
    throws javax.management.InvalidAttributeValueException
  {
    String _copy = param0;
    _copy = weblogic.management.configuration.LegalHelper.checkClassName(_copy);
    param0 = _copy;
    _ProviderClassName = param0;
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=setSupportedTypes)
   *
   */
  public void setSupportedTypes(String[] param0)
    throws javax.management.InvalidAttributeValueException
  {
    param0 = (param0 == null) ? new String[0] : param0;
    _getHelper()._ensureNonNullElements(param0);
    _SupportedTypes = param0;
  }

  /**
   * No description provided.
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=getActiveTypes)
   *
   * @xsdgen:element.name active-type
   * @xsdgen:element.required false
   * @xsdgen:element.nillable true
   * @dynamic false
   */
  public String[] getActiveTypes() {
    return _ActiveTypes;
  }

  /**
   * No description provided.
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=getDescription)
   *
   * @xsdgen:element.exclude
   * @transient
   */
  public String getDescription() {
    return _Description;
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=isActiveTypesInherited)
   *
   * return true if the value of property ActiveTypes is inherited from template
   */
  public boolean isActiveTypesInherited() {
    return false;
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=isActiveTypesSet)
   *
   * @xsdgen:isSetMethodFor active-type
   */
  public boolean isActiveTypesSet() {
    return _isSet(9);
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=isDescriptionInherited)
   *
   * return true if the value of property Description is inherited from template
   */
  public boolean isDescriptionInherited() {
    return false;
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=isDescriptionSet)
   *
   * @xsdgen:isSetMethodFor description
   */
  public boolean isDescriptionSet() {
    return _isSet(3);
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=setDescription)
   *
   */
  public void setDescription(String param0)
    throws javax.management.InvalidAttributeValueException
  {
    _Description = param0;
  }

  /**
   * No description provided.
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=getVersion)
   *
   * @xsdgen:element.exclude
   * @transient
   */
  public String getVersion() {
    return _Version;
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=isVersionInherited)
   *
   * return true if the value of property Version is inherited from template
   */
  public boolean isVersionInherited() {
    return false;
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=isVersionSet)
   *
   * @xsdgen:isSetMethodFor version
   */
  public boolean isVersionSet() {
    return _isSet(4);
  }

  /**
   * No description provided.
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=setActiveTypes)
   *
   */
  public void setActiveTypes(String[] param0)
    throws javax.management.InvalidAttributeValueException
  {
    param0 = (param0 == null) ? new String[0] : param0;
    _getHelper()._ensureNonNullElements(param0);
    String[] _oldVal = _ActiveTypes;
    _ActiveTypes = param0;
    _postSet(9, _oldVal, param0);
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=setVersion)
   *
   */
  public void setVersion(String param0)
    throws javax.management.InvalidAttributeValueException
  {
    _Version = param0;
  }

  /**
   * No description provided.
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=getBase64DecodingRequired)
   *
   * @xsdgen:element.name base64-decoding-required
   * @xsdgen:element.required false
   * @xsdgen:element.nillable true
   * @xsdgen:element.default false
   * @dynamic false
   */
  public boolean getBase64DecodingRequired() {
    return _Base64DecodingRequired;
  }

  /**
   * Returns the realm that contains this security provider.
 Returns null if this security provider is not contained by a realm.
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=getRealm)
   *
   * @xsdgen:element.exclude
   * @transient
   */
  public weblogic.management.security.RealmMBean getRealm() {
    return _customizer.getRealm();
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=isBase64DecodingRequiredInherited)
   *
   * return true if the value of property Base64DecodingRequired is inherited from template
   */
  public boolean isBase64DecodingRequiredInherited() {
    return false;
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=isBase64DecodingRequiredSet)
   *
   * @xsdgen:isSetMethodFor base64-decoding-required
   */
  public boolean isBase64DecodingRequiredSet() {
    return _isSet(10);
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=isRealmInherited)
   *
   * return true if the value of property Realm is inherited from template
   */
  public boolean isRealmInherited() {
    return false;
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=isRealmSet)
   *
   * @xsdgen:isSetMethodFor realm
   */
  public boolean isRealmSet() {
    return _isSet(5);
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=setRealm)
   *
   */
  public void setRealm(weblogic.management.security.RealmMBean param0)
    throws javax.management.InvalidAttributeValueException
  {
    _Realm = param0;
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=getName)
   *
   * @xsdgen:element.name name
   * @xsdgen:element.required false
   * @xsdgen:element.nillable true
   * @xsdgen:element.default SimpleSampleIdentityAsserter
   * @dynamic false
   */
  public String getName() {
    return _Name;
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=isNameInherited)
   *
   * return true if the value of property Name is inherited from template
   */
  public boolean isNameInherited() {
    return false;
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=isNameSet)
   *
   * @xsdgen:isSetMethodFor name
   */
  public boolean isNameSet() {
    return _isSet(6);
  }

  /**
   * No description provided.
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=setBase64DecodingRequired)
   *
   */
  public void setBase64DecodingRequired(boolean param0)
    throws javax.management.InvalidAttributeValueException
  {
    boolean _oldVal = _Base64DecodingRequired;
    _Base64DecodingRequired = param0;
    _postSet(10, _oldVal, param0);
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=setName)
   *
   */
  public void setName(String param0)
    throws javax.management.InvalidAttributeValueException
  {
    param0 = (param0 == null) ? null : param0.trim();
    String _oldVal = _Name;
    _Name = param0;
    _postSet(6, _oldVal, param0);
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=getCompatibilityObjectName)
   *
   * @xsdgen:element.name compatibility-object-name
   * @xsdgen:element.required false
   * @xsdgen:element.nillable true
   * @dynamic false
   */
  public String getCompatibilityObjectName() {
    return _customizer.getCompatibilityObjectName();
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=isCompatibilityObjectNameInherited)
   *
   * return true if the value of property CompatibilityObjectName is inherited from template
   */
  public boolean isCompatibilityObjectNameInherited() {
    return false;
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=isCompatibilityObjectNameSet)
   *
   * @xsdgen:isSetMethodFor compatibility-object-name
   */
  public boolean isCompatibilityObjectNameSet() {
    return _isSet(7);
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=setCompatibilityObjectName)
   *
   */
  public void setCompatibilityObjectName(String param0)
    throws javax.management.InvalidAttributeValueException
  {
    param0 = (param0 == null) ? null : param0.trim();
    String _oldVal = _CompatibilityObjectName;
    _CompatibilityObjectName = param0;
    _postSet(7, _oldVal, param0);
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=_getKey)
   *
   */
  public Object _getKey() {
    return super._getKey();
  }

  /**
   * 
   * (Interface=examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean Attribute=_validate)
   *
   */
  public void _validate()
    throws IllegalArgumentException
  {
    super._validate();
  }



 





  protected void _unSet(int idx) {
    if (!_initializeProperty(idx)) {
      super._unSet(idx);
    } else {
      _markSet(idx, false);
    }
  }


  /**
   * @return new instance of helper
   */
  protected AbstractDescriptorBeanHelper _createHelper() {
    return new Helper(this);
  }

  /**
   * @return true if any property is set
   */
  public boolean _isAnythingSet() {
    return super._isAnythingSet()
      ;
  }



  /**
   * @return true if property initialized, false idx refers to a property
   * handled by superclass
   */
  private boolean _initializeProperty(int idx) {
    boolean initOne = idx > -1;
    if (!initOne) {
      idx = 9;
    }
    try {
      switch (idx) {
      case 9:
        _ActiveTypes = StringHelper.split("SamplePerimeterAtnToken");
        if (initOne) break;
      case 10:
        _Base64DecodingRequired = false;
        if (initOne) break;
      case 7:
        _CompatibilityObjectName = null;
        if (initOne) break;
      case 3:
        _Description = "WebLogic Simple Sample Identity Asserter Provider";
        if (initOne) break;
      case 6:
        _Name = "SimpleSampleIdentityAsserter";
        if (initOne) break;
      case 2:
        _ProviderClassName = "examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterProviderImpl";
        if (initOne) break;
      case 5:
        _Realm = null;
        if (initOne) break;
      case 8:
        _SupportedTypes = StringHelper.split("SamplePerimeterAtnToken");
        if (initOne) break;
      case 4:
        _Version = "1.0";
        if (initOne) break;
      default:
        if (initOne) return false;
      }
      return true;
    } catch (RuntimeException e) {
      throw e;
    } catch (Exception e) {
      throw (Error)new AssertionError("Impossible Exception").initCause(e);
    }
  }


  /**
   * This helper class contains methods that are used infrequently and
   * can be easily separated from the bean implementations.  It is loaded
   * on demand to minimize memory usage.
   *
   * @xsdgen:complexType.exclude
   */
  protected static class Helper
    extends weblogic.management.security.authentication.IdentityAsserterMBeanImpl.Helper
  {
    private SimpleSampleIdentityAsserterMBeanImpl bean;

    protected Helper(SimpleSampleIdentityAsserterMBeanImpl bean) {
      super(bean);
      this.bean = bean;
    }

    /**
     * @return property name indexed by propIndex.
     */
    public String getPropertyName(int propIndex) {
      switch (propIndex) {
      case 9: return "ActiveTypes";
      case 10: return "Base64DecodingRequired";
      case 7: return "CompatibilityObjectName";
      case 3: return "Description";
      case 6: return "Name";
      case 2: return "ProviderClassName";
      case 5: return "Realm";
      case 8: return "SupportedTypes";
      case 4: return "Version";
      default: return super.getPropertyName(propIndex);
      }
    }


    /**
     * @return property index of propName.
     */
    public int getPropertyIndex(String propName) {
      if (false) return -1;
      else if (propName.equals("ActiveTypes")) return 9;
      else if (propName.equals("Base64DecodingRequired")) return 10;
      else if (propName.equals("CompatibilityObjectName")) return 7;
      else if (propName.equals("Description")) return 3;
      else if (propName.equals("Name")) return 6;
      else if (propName.equals("ProviderClassName")) return 2;
      else if (propName.equals("Realm")) return 5;
      else if (propName.equals("SupportedTypes")) return 8;
      else if (propName.equals("Version")) return 4;
      else return super.getPropertyIndex(propName);
    }

    /**
     * @return iterator over all children
     */
    public Iterator getChildren() {
      List iterators = new ArrayList();
      return new CombinedIterator(iterators);
    }

    /**
     * Compute hash value for version helper
     */
    protected long computeHashValue(CRC32 crc) {
      try {
        StringBuffer buf = new StringBuffer();
        long superValue = super.computeHashValue(crc);
        if (superValue != 0) {
          buf.append(String.valueOf(superValue));
        }

        long childValue = 0;
        if (bean.isActiveTypesSet()){
          buf.append("ActiveTypes");
          buf.append(Arrays.toString(ArrayUtils.copyAndSort(bean.getActiveTypes())));
        }
        if (bean.isBase64DecodingRequiredSet()){
          buf.append("Base64DecodingRequired");
          buf.append(String.valueOf(bean.getBase64DecodingRequired()));
        }
        if (bean.isCompatibilityObjectNameSet()){
          buf.append("CompatibilityObjectName");
          buf.append(String.valueOf(bean.getCompatibilityObjectName()));
        }
        if (bean.isDescriptionSet()){
          buf.append("Description");
          buf.append(String.valueOf(bean.getDescription()));
        }
        if (bean.isNameSet()){
          buf.append("Name");
          buf.append(String.valueOf(bean.getName()));
        }
        if (bean.isProviderClassNameSet()){
          buf.append("ProviderClassName");
          buf.append(String.valueOf(bean.getProviderClassName()));
        }
        if (bean.isRealmSet()){
          buf.append("Realm");
          buf.append(String.valueOf(bean.getRealm()));
        }
        if (bean.isSupportedTypesSet()){
          buf.append("SupportedTypes");
          buf.append(Arrays.toString(ArrayUtils.copyAndSort(bean.getSupportedTypes())));
        }
        if (bean.isVersionSet()){
          buf.append("Version");
          buf.append(String.valueOf(bean.getVersion()));
        }
        crc.update(buf.toString().getBytes());
        return crc.getValue();
      } catch (Exception e) {
        throw (Error)new AssertionError("Impossible Exception").initCause(e);
      }
    }
    /**
     * Compute difference between this and other
     */
    protected void computeDiff(AbstractDescriptorBean other) {
      try {
        super.computeDiff(other);
      SimpleSampleIdentityAsserterMBeanImpl otherTyped = (SimpleSampleIdentityAsserterMBeanImpl)other;
      computeDiff("ActiveTypes", bean.getActiveTypes(), otherTyped.getActiveTypes(), false);
      computeDiff("Base64DecodingRequired", bean.getBase64DecodingRequired(), otherTyped.getBase64DecodingRequired(), false);
      computeDiff("CompatibilityObjectName", bean.getCompatibilityObjectName(), otherTyped.getCompatibilityObjectName(), false);
      computeDiff("Name", bean.getName(), otherTyped.getName(), false);
      } catch (Exception e) {
        throw (Error)new AssertionError("Impossible Exception").initCause(e);
      }
    }

    protected void applyPropertyUpdate(BeanUpdateEvent event, PropertyUpdate update) {
      try {
        SimpleSampleIdentityAsserterMBeanImpl original = (SimpleSampleIdentityAsserterMBeanImpl)event.getSourceBean();
        SimpleSampleIdentityAsserterMBeanImpl proposed = (SimpleSampleIdentityAsserterMBeanImpl)event.getProposedBean();
        String prop = update.getPropertyName();
        int type = update.getUpdateType();
        if (update.isDerivedUpdate()) {
          return;
        }
        if (prop.equals("ActiveTypes")) {
          original.setActiveTypes(proposed.getActiveTypes());
          original._conditionalUnset(update.isUnsetUpdate(), 9);
        } else
        if (prop.equals("Base64DecodingRequired")) {
          original.setBase64DecodingRequired(proposed.getBase64DecodingRequired());
          original._conditionalUnset(update.isUnsetUpdate(), 10);
        } else
        if (prop.equals("CompatibilityObjectName")) {
          original._conditionalUnset(update.isUnsetUpdate(), 7);
        } else
        if (prop.equals("Description")) {
        } else
        if (prop.equals("Name")) {
          original.setName(proposed.getName());
          original._conditionalUnset(update.isUnsetUpdate(), 6);
        } else
        if (prop.equals("ProviderClassName")) {
        } else
        if (prop.equals("Realm")) {
        } else
        if (prop.equals("SupportedTypes")) {
        } else
        if (prop.equals("Version")) {
        } else
        {
          super.applyPropertyUpdate(event, update);
        }
      // FIXME ehalpern - hack to handle cases where setters throw
      // javax.management.InvalidAttributeValueException.
      } catch (RuntimeException e) {
        throw e;
      } catch (Exception e) {
        throw (Error)new AssertionError("Impossible Exception").initCause(e);
      }
    }

    protected AbstractDescriptorBean finishCopy(
    AbstractDescriptorBean initialCopy, boolean includeObsolete, List excludeProps
    ) {
      Object o;
      try {
        SimpleSampleIdentityAsserterMBeanImpl copy = (SimpleSampleIdentityAsserterMBeanImpl)initialCopy;
        super.finishCopy(copy, includeObsolete, excludeProps);
        if ((excludeProps == null || !excludeProps.contains("ActiveTypes")) && bean.isActiveTypesSet()) {
          o = bean.getActiveTypes();
          copy.setActiveTypes((o == null) ? null : (String[])((String[])o).clone());
        }
        if ((excludeProps == null || !excludeProps.contains("Base64DecodingRequired")) && bean.isBase64DecodingRequiredSet()) {
          copy.setBase64DecodingRequired((boolean)bean.getBase64DecodingRequired());
        }
        if ((excludeProps == null || !excludeProps.contains("CompatibilityObjectName")) && bean.isCompatibilityObjectNameSet()) {
        }
        if ((excludeProps == null || !excludeProps.contains("Name")) && bean.isNameSet()) {
          copy.setName((String)bean.getName());
        }
        return copy;
      // FIXME ehalpern - hack to handle cases where setters throw
      // javax.management.InvalidAttributeValueException.
      } catch (RuntimeException e) {
        throw e;
      } catch (Exception e) {
        throw (Error)new AssertionError("Impossible Exception").initCause(e);
      }
    }

    protected void inferSubTree(Class clazz, Object annotation) {
    	super.inferSubTree(clazz, annotation);
    	Object currentAnnotation = null;
                   		inferSubTree(bean.getRealm(), clazz, annotation);
             }
  }


  // FIXME ec@weblogic.com 01-Feb-05 -- no longer used. Remove when ADB method is removed
  public weblogic.descriptor.internal.Munger.SchemaHelper _getSchemaHelper() {
    return null;
  }

  // FIXME ec@weblogic.com 01-Feb-05 -- remove
  public String _getElementName(int propIndex) {
    return _getSchemaHelper2().getElementName(propIndex);
  }


  protected String getTargetNamespace() {
    return "http://xmlns.oracle.com/weblogic/security/extension";
  }

  private static SchemaHelper2 _schemaHelper;
  public weblogic.descriptor.internal.SchemaHelper _getSchemaHelper2() {
    if (_schemaHelper == null)
	_schemaHelper = new SchemaHelper2();
    return _schemaHelper;
  }

   // new schema helper
  /**
   * @xsdgen:complexType.exclude
   */
  public static class SchemaHelper2
   extends weblogic.descriptor.internal.AbstractSchemaHelper2
   implements weblogic.descriptor.internal.SchemaHelper
  {
    public int getPropertyIndex(String s) {
      switch(s.length()) {
      case 11:
        if (false) return -1;
        else if (s.equals("active-type"))
          return 9;
        else if (s.equals("description"))
          return 3;
        break;
      case 24:
        if (false) return -1;
        else if (s.equals("base64-decoding-required"))
          return 10;
        break;
      case 25:
        if (false) return -1;
        else if (s.equals("compatibility-object-name"))
          return 7;
        break;
      case 4:
        if (false) return -1;
        else if (s.equals("name"))
          return 6;
        break;
      case 19:
        if (false) return -1;
        else if (s.equals("provider-class-name"))
          return 2;
        break;
      case 5:
        if (false) return -1;
        else if (s.equals("realm"))
          return 5;
        break;
      case 14:
        if (false) return -1;
        else if (s.equals("supported-type"))
          return 8;
        break;
      case 7:
        if (false) return -1;
        else if (s.equals("version"))
          return 4;
        break;
      default:
        break;
      }
      return super.getPropertyIndex(s);
    }

    public weblogic.descriptor.internal.SchemaHelper getSchemaHelper(int propIndex) {
      switch(propIndex) {
      default:
        return super.getSchemaHelper(propIndex);
      }
    }


    public String getRootElementName() {
      return "simple-sample-identity-asserterm";
    }

    public String getElementName(int propIndex) {
      switch (propIndex) {
        case 9: return "active-type";
        case 10: return "base64-decoding-required";
        case 7: return "compatibility-object-name";
        case 3: return "description";
        case 6: return "name";
        case 2: return "provider-class-name";
        case 5: return "realm";
        case 8: return "supported-type";
        case 4: return "version";
        default: return super.getElementName(propIndex);
      }
    }


    public boolean isArray(int propIndex) {
      switch(propIndex) {
      case 9:
        return true;
      case 8:
        return true;
      default:
        return super.isArray(propIndex);
      }
    }




    public boolean isBean(int propIndex) {
      switch(propIndex) {
      default:
        return super.isBean(propIndex);
      }
    }










  }




  public String wls_getInterfaceClassName() {
    return "examples.security.providers.identityassertion.simple.SimpleSampleIdentityAsserterMBean"; 
  }

}
